{{- if .Values.id_rsa.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hound.fullname" . }}-ssh-key
  labels:
    app: {{ template "hound.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  id_rsa: {{ .Values.id_rsa.key }}
{{- end }}
